export * from "./tenants";
export * from "./courses";
export * from "./students";
export * from "./settings";
export * from "./activity";
export * from "./instructors";
export * from "./lesson_completions";
export * from "./quizzes";
export * from "./enrollments";
export * from "./categories";
export * from "./academy_profile";
export * from "./certificates";
export * from "./coupons";
export * from "./admin_users";
export * from "./notification"